version: '3.8'

services:
  journal:
    build: .
    env_file:
      - .env
    ports:
      - '3019:3019'
    environment:
      - PORT=3019
      - DATABASE_URL=postgresql://neondb_owner:npg_n8XHwNRvA6ge@ep-yellow-haze-a2l3hhsf-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
      - NEXTAUTH_SECRET=UYJt9kehVQw2TppG
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - TAILWIND_DISABLE_TOUCH=true
      - TAILWIND_DISABLE_OXIDE=1
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: journal
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '59434:5432'

volumes:
  postgres:
